server:
  port: 9500

logging:
  level:
    org.springframework.web: DEBUG
    #  pattern:
    #    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"

spring:
  application.name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"  # Cambia esto al origen permitido
            allowedMethods: "*"
            allowedHeaders: "*"  # Permitir todas las cabeceras
      routes:
        - id: resources-service-route-test
          uri: http://localhost:8080  # Cambia esto al origen de tus servicios
          predicates:
            Path=/api/**
          filters:
            - StripPrefix=1



# disable eureka by default
eureka:
  client:
    enabled: false